name: Build compact DuckDB

on:
  schedule:
    - cron: "30 0 * * *"          # nightly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build connectly.duckdb via Python
        run: |
          pip install duckdb
          python - <<'PY'
          import duckdb, glob, pathlib, itertools, os
          con = duckdb.connect("connectly.duckdb")
          print("▶ building camp table...")
          camp_files = list(itertools.chain.from_iterable(
              glob.glob(p) for p in [
                  "parquet_trim/dispatch_date=*/data_0.parquet",
                  "parquet_trim/msg_*.parquet",
                  "parquet_output/dispatch_date=*/data_0*.parquet",
              ]))
          con.execute(f"""
            CREATE OR REPLACE TABLE camp AS
            SELECT * FROM read_parquet(
              [{', '.join(repr(pathlib.Path(f).as_posix()) for f in camp_files)}],
              union_by_name=true
            );
          """)
          print("▶ building act table...")
          act_files = list(itertools.chain.from_iterable(
              glob.glob(p) for p in [
                  "activity_trim/act_*.parquet",
                  "activity_chunks/activity_data_*.parquet",
              ]))
          if act_files:
              con.execute(f"""
                CREATE OR REPLACE TABLE act AS
                SELECT * FROM read_parquet(
                  [{', '.join(repr(pathlib.Path(f).as_posix()) for f in act_files)}],
                  union_by_name=true
                );
              """)
          else:
              con.execute("CREATE OR REPLACE TABLE act(user VARCHAR, activity_date DATE);")
          con.close()
          print("✅ connectly.duckdb built")
          PY

      - name: Commit DB
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add connectly.duckdb
          git commit -m "CI: refresh compact DB" || echo "No changes"
          git push
