name: Build slim DuckDB

on:
  workflow_dispatch:     # run manually
  schedule:
    - cron: "30 1 * * *" # or nightly at 01:30 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install duckdb pandas pyarrow

      - name: Run build_duckdb.py
        run: python build_duckdb.py

      - name: Commit updated DB
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add connectly_slim.duckdb
          git commit -m "CI: rebuild slim DuckDB" || echo "No changes"
          git push
