name: Build compact DuckDB via Python

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # runs every day at 1am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install DuckDB
        run: pip install duckdb

      - name: Build DuckDB from parquet
        run: |
          python - <<'PY'
          import duckdb, glob, pathlib, itertools

          print("▶ Building compact DuckDB")

          con = duckdb.connect("connectly.duckdb")

          # Campaign files
          camp_files = list(itertools.chain.from_iterable(
              glob.glob(p) for p in [
                  "parquet_trim/dispatch_date=*/data_0.parquet",
                  "parquet_trim/msg_*.parquet",
                  "parquet_output/dispatch_date=*/data_0*.parquet"
              ]
          ))
          con.execute(f"""
          CREATE OR REPLACE TABLE camp AS
          SELECT 
            customer_external_id,
            dispatched_at,
            delivered,
            button_responses,
            link_clicks,
            business_id,
            sendout_name
          FROM read_parquet(
            [{','.join(repr(str(pathlib.Path(p))) for p in camp_files)}],
            union_by_name=true
          )
          """)

          # Activity files
          act_files = glob.glob("activity_chunks/activity_data_*.parquet")
          con.execute(f"""
          CREATE OR REPLACE TABLE act AS
          SELECT 
            COALESCE(CAST(guardian_phone AS VARCHAR),
                     CAST(moderator_phone AS VARCHAR),
                     CAST(user_phone AS VARCHAR)) AS user_phone,
            activity_date
          FROM read_parquet(
            [{','.join(repr(str(pathlib.Path(p))) for p in act_files)}],
            union_by_name=true
          )
          """)
          print("✅ Finished building DuckDB")
          PY

      - name: Commit DB file
        run: |
          git config u
